spring:
  application:
    name: game-inven
  security:
    user:
      name: user
      password: 1234
  datasource:
    url: jdbc:mysql://192.168.219.100:3306/inven
    username: blackcow
    password: blackcow25!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        type: warn
    hibernate:
      ddl-auto: none
      naming:
        ##설정한 테이블명 그대로를 사용(대/소문자)
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    org:
      springframework: warn
      hibernate:
        SQL: warn
        orm.jdbc.bind: warn
      jdbc.bind: warn

jwt:
  secret: CcMIo0+0OlAeP9Z/AfN1qq3hA8fYHIhY513xy1N9B9w=

server:
  port: 8080
  address: 0.0.0.0