name: Deploy to Tomcat via SSH

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create application.yml
      run: echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
  
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (Skip Tests)
      run: mvn clean package -DskipTests

    - name: Upload WAR file to Server via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        port: 20
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "target/*.war"
        target: "/opt/tomcat/webapps/app.war"

    - name: Restart Tomcat Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        port: 20
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          sudo systemctl restart tomcat

