name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Tomcat
      env:
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD}}
      run: |
        curl -v --user "admin:$TOMCAT_PASSWORD" --upload-file target/*.war \
        "http://58.78.52.20:8888/manager/text/deploy?path=/your-app-name&update=true"
